### ISSUE TITLE
Can't color samples in ordination plot

### ISSUE THREAD

**Issue by mlangill** [joey711/shiny-phyloseq#50]
I have tried a couple of different datasets where there is just one qualitative grouping for the samples (3 groups). I can colour by samples using this metadata for all of the plots EXCEPT the ordination plots. I keep getting this error in the terminal:

    Warning in plot_ordination(physeq = physeq_ord(), ordination = get_ord(),  : 
    Color variable was not found in the available data you provided.No color mapped.
    No available covariate data to map on the points for this plot `type`

**Comment by joey711** [comment]
I cannot reproduce this bug. Will close for now. The latest version of shiny-phyloseq should show color mapping that works for ordination panel.
