### ISSUE TITLE
Errors after re-install

### ISSUE THREAD

**Issue by spholmes** [joey711/shiny-phyloseq#52]
I just installed a clean install of R (3.1.2) and BioC(3.0)
When I install shiny-phyloseq from Github, I get, as well as the same old warnings as before,
 the following :
Error in read.table(text = QIIMEDB_files_list, stringsAsFactors = FALSE) : 
  no lines available in input
Error in sum(nonEmpty) : invalid 'type' (list) of argument
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.

phyloseq_1.10.0 

Giving a talk and demo about this Monday at WEHI (where the lima edgeR people are), I'd be happy not to show errors all the way through...

**Comment by joey711** [comment]
Sorry, I haven't been checking on this as much as phyloseq and others lately...

Unfortunately, this sounds like a QIIME-DB error. I'll have to look into it further, but it wouldn't surprise me if they took down or moved their ftp location. Pretty annoying. I'll see if I can squeeze some time in later today to check in more detail. 

Quick fix:
The QIIME-DB stuff is nice, but not necessary to create an example from local files, even just the self-included demo files. It should be possible to surgically remove the QIIME-DB stuff from IO and server files and "move on". In light of what we know about OTU clustering and rarefying, not-using the standard QIIME pipeline output is probably a good thing...

**Comment by spholmes** [comment]
This issue is due to the fact that the current shiny package uses Bootstrap 3 and the download includes an old version of bootstrap.css, by just renaming the old bootstrap.css I was able to have most of the commands behave, the only thing that seems different in my preliminary testing is that the nice color scheme has gone away.
I won't close the issue until we take out the bootstrap.css file.

**Comment by joey711** [comment]
Thanks, Susan, and sorry for the trouble! I'll see to updating the css, fixing any lingering issues from that change, and perhaps picking a new color scheme.

Have a preference on the updated color scheme?

**Comment by spholmes** [comment]
I liked the red and we need to see the shiny-phyloseq logo.
Hadley gave a super nice talk, as usual, his tidyr - plyr - ggvis
pipeline looks really cool (not all finished yet)

I saw another issue with the placement of the screeplot in the ordinations
(they come up too high), if you fix it today, let me know, my talk is
tomorrow morning early,
with the chill factor it's -35 C here, thats really cold!!


On Mon, Feb 23, 2015 at 11:43 AM, Paul J. McMurdie <notifications@github.com
> wrote:

> Thanks, Susan, and sorry for the trouble! I'll see to updating the css,
> fixing any lingering issues from that change, and perhaps picking a new
> color scheme.
>
> Have a preference on the updated color scheme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/shiny-phyloseq/issues/52#issuecomment-75579842>
> .
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
The last few commits should have solved these issues (ordination/scree plot, and most of the bootstrap-3 formatting).
There are a few panel-specific formatting issues to fix, but all aesthetic at this point.

I also turned-off the QIIME-DB interface. QIIME-DB is completely down. Google forum questions about this state that they had a big hardware failure, and rather than get QIIME-DB back up, they are migrating everything to a new platform called Qiita...
