### ISSUE TITLE
shinythemese

### ISSUE THREAD

**Issue by zachcp** [joey711/shiny-phyloseq#54]
Installing shiny-phyloseq I encounter the following error:
```
Downloading https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
Loading required package: shiny
Error in library("shinythemes") : 
 there is no package called ‘shinythemes’
```
Its simple enough to install `shinythemes` but can this be pulled in automatically?

thanks,
zach cp

**Comment by spholmes** [comment]
Ditto, same problem, once you install with
install.packages("shinythemes")
there is no problem, but it is not documented.

**Comment by joey711** [comment]
Sorry, I'll make sure the installation script has this updated, and that the dependency is clear.

**Comment by joey711** [comment]
8a66790f31695e78aaadecdc2c72cdeb0c2dbfb1
Done.
Sorry that took me so long!
