### ISSUE TITLE
How set the parse function for the taxonomy string

### ISSUE THREAD

**Issue by mdehollander** [joey711/shiny-phyloseq#56]
If I load a custom BIOM file, the tax_table contains Rank1, Rank2 etc. Directly in R I can set the colnames, but in the shiny GUI this is not possible. I assume that the biom file is loaded with import_biom and the parse_taxonomy_default function? Would it be possible to support also the greengenes formatting?

Reproducible example:
1. Download a biom file from Qiita, for example: http://qiita.microbio.me/download/80 (you need to be logged in)
2. By default this is in hdf5 format, so convert it to json format
3. Upload to shiny-phyloseq
4. Look at the taxonomy table

**Comment by joey711** [comment]
Thanks @mdehollander ... You can always save as a phyloseq object in native "RData" format using the `save` command. Then upload that instead. This also means you can do your own custom filtering, labelling, cleaning in phyloseq beforehand. Useful for teaching examples, etc., where the exposed stuff in shiny-phyloseq is either not there or kindof tedious to repeat over and over.

**Comment by joey711** [comment]
BTW, the HDF5-biom thing is nearly fixed. I'll try to push that to shiny-phyloseq first so you can avoid that series of steps.
