### ISSUE TITLE
Problem with runGitHub launch

### ISSUE THREAD

**Issue by ericamh** [joey711/shiny-phyloseq#60]
Had this issue with launching/installing:

Downloading https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
wget: invalid option -- 'f'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
Error in shiny::runUrl("https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz") : 
  Failed to download URL https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
In addition: Warning message:
In utils::download.file(url, method = method, ...) :
  download had nonzero exit status

I'm running RStudio 0.99.483 and R 3.2.2 on a Mac (Yosemite 10.10.5).

I solved this problem temporarily by downloading the repository locally and using shiny::runApp() to run it from the local directory.

**Comment by pwelliott** [comment]
I fixed this same issue by uninstalling wget

**Comment by joey711** [comment]
This should be fixed now. Please post an update with system info if this is not the case.
