### ISSUE TITLE
DESeq2 rlog normalized microbiome data for diversity and PCoA analysis

### ISSUE THREAD

**Issue by plsysu** [joey711/shiny-phyloseq#63]
Hi yours,

My data have two batches. I used DESeq2 to normalize the count data and model the batch effect with “Design=~Batch+Treatment”. Then, I used rlog function the same as Shiny-phyloseq except I added another step (removeBatchEffect).

  
```
rld <- DESeq2::rlog(dds, blind = TRUE, fast = TRUE)
rlogMat <- GenomicRanges::assay(rld)
library(limma)
rld_remove_batch <- removeBatchEffect(rlogMat,batch = colData $Batch)
physeq1 = physeq
otu_table(physeq1) <- otu_table(rld_remove_batch, taxa_are_rows = TRUE)

```
My questions is :
Is it right to perform richness analysis (alpha diversity analysis) and PCoA analysis using the updated physeq1 object ? The OTU table in phyloseq1 object have both positive and negative values. The values doesn’t mean count any more. So, how to analyze alpha and beta diversity on data with batch effect ?
             
Thanks !

Regards,
Peng Li

**Comment by spholmes** [comment]
Peng,
It's OK to do PCOA on transformed data and diversity analyses will be
nonsense,
Susan

On Mon, Mar 14, 2016 at 6:57 PM, Peng Li <notifications@github.com> wrote:

> Hi yours,
>
> My data have two batches. I used DESeq2 to normalize the count data and
> model the batch effect with “Design=~Batch+Treatment”. Then, I used rlog
> function the same as Shiny-phyloseq except I added another step
> (removeBatchEffect).
>
> rld <- DESeq2::rlog(dds, blind = TRUE, fast = TRUE)
> rlogMat <- GenomicRanges::assay(rld)
> library(limma)
> rld_remove_batch <- removeBatchEffect(rlogMat,batch = colData $Batch)
> physeq1 = physeq
> otu_table(physeq1) <- otu_table(rld_remove_batch, taxa_are_rows = TRUE)
>
>
> My questions is :
> Is it right to perform richness analysis (alpha diversity analysis) and
> PCoA analysis using the updated physeq1 object ? The OTU table in phyloseq1
> object have both positive and negative values. The values doesn’t mean
> count any more. So, how to analyze alpha and beta diversity on data with
> batch effect ?
>
> Thanks !
>
> Regards,
> Peng Li
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/joey711/shiny-phyloseq/issues/63
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by plsysu** [comment]
Susan,
Yes, I got it. Is there any way to perform diversity analysis?
