### ISSUE TITLE
Problem installing shiny-phyloseq

### ISSUE THREAD

**Issue by robertadegrandi** [joey711/shiny-phyloseq#79]
Hi, I am trying to install shiny-phyloseq  using the command suggested below
shiny::runGitHub("shiny-phyloseq","joey711").
but it return this error:
Downloading https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
Error in setwd(exdir) : cannot change working directory

Previously I  correctly installed the shiny package with the command install.packages("shiny").
Similarly, I installed phyloseq package using as command
source("https://bioconductor.org/biocLite.R")
biocLite("phyloseq").
Both packages are present in my library.

I don't know how to risolve the Error reported above. Can someone help me, please?
Thank,
Roberta

**Comment by joey711** [comment]
Just fixed. please try again.
